### ISSUE TITLE
Compilation error :geometricCtrlConfig.h: No such file or directory

### ISSUE THREAD

**Issue by germal** [Jaeyoung-Lim/mavros_controllers#92]
Hello

Hi !
I just found the following compilation error  :

In file included from /home/ubuntu/catkin_ws/src/mavros_controllers/geometric_controller/src/geometric_controller.cpp:3:0:
/home/ubuntu/catkin_ws/src/mavros_controllers/geometric_controller/include/geometric_controller/geometric_controller.h:34:54: fatal error: geometric_controller/geometricCtrlConfig.h: No such file or directory

and ìndeed the header file is not present .
Clould you please advice ?
Thanks a lot !

![immagine](https://user-images.githubusercontent.com/47027729/59422070-077f2d80-8dd0-11e9-8cbe-53df460eec51.png)

**Comment by Jaeyoung-Lim** [comment]
@germal It seems like a regression from #90 . Could you revert the PR for the moment? I am working on a fix.

**Comment by Jaeyoung-Lim** [comment]
@germal Could you try again with the current master? I believe the issue is fixed

**Comment by germal** [comment]
@Jaeyoung-Lim  , it compiles perfectly ! Thank you very much !
